### ISSUE TITLE
Validation of README instructions

### ISSUE THREAD

**Issue by joe-plumb** [joe-plumb/mdw-azure-terraform#8]

**Comment by ejones18** [comment]
### Validation of README set-up instructions - changes / additions ###

- Add terraform task extension from DevOps marketplace
- ```./sharedinfra/providers.tf``` - update version of azuread to ```hashicorp/azuread v2.12.0```
- ```./sharedinfra/kv.tf``` - fix bug, change tenant_id name -> ```tf-ado-syn-spn-tenant-id```
- ```./sharedinfra/sp.tf``` - remove ```azuread_service_principal_password```, create ```azuread_application_password``` instead - ```application_object_id = azuread_application.ado_tf_deployment_sp.object_id```
- ```./sharedinfra/roleassignments.tf ```- update principle_id  for azurerm role assignment-> ```azuread_service_principal.ado_tf_deployment_sp.object_id```
- ```./sharedinfra/roleassignments.tf``` - change 'depends on' tag for azurerm role assignment -> ```azuread_service_principal.ado_tf_deployment_sp```
- ```./sharedinfra/outputs.tf``` - update sp secret -> ```azuread_application_password.ado_tf_deployment_sp.value```
- ```./sharedinfra/outputs.tf``` - update tenant id -> ```data.azurerm_subscription.current.tenant_id```
- ```./sharedinfra/kv.tf``` - update 'depends on' tag for following client_id, tenant_id and client secret -> ```azuread_application_password.ado_tf_deployment_sp```
- ```./sharedinfra/outputs.tf``` - update tenant_id value -> ```data.azurerm_subscription.current.tenant_id```
- ```./sharedinfra/outputs.tf``` - update client secret value -> ```azuread_application_password.ado_tf_deployment_sp.value```
- ```./sharedinfra/kv.tf``` - added kv rights for sp ```azuread_service_principal.ado_tf_deployment_sp.object_id``` with secret permissions ```"get", "list"```
- ```./sharedinfra/kv.tf``` - changed client_id value to ```azuread_service_principal.ado_tf_deployment_sp.application_id```
- Re-ordering of steps - step 9 r.e. creating service connection needs to go before creating the kv-backed vg in order to verify connection / permissions

![pipeline_permissions](https://user-images.githubusercontent.com/61836666/145793968-7694e7f4-42c0-4552-978a-7883c1d8e276.png)
Section needed to cover pipeline permissions as seen in the above snippet
